name: Share data between jobs 2

on:
  workflow_run:
    workflows: ["Share data between jobs"]
    types: [completed]

jobs:
  job_2:
    name: Multiply by 9
    runs-on: windows-latest
    steps:
      - name: Sleep for 10 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: run1.yml
          commit: ${{github.event.workflow_run.head.sha}}
          workflow_conclusion: success
          name: homework
      - shell: bash
        run: |
          value=`cat math-homework.txt`
          expr $value \* 9 > math-homework.txt
      - name: Upload math result for job 2
        uses: actions/upload-artifact@v2
        with:
          name: homework-2
          path: math-homework.txt
