name: Share data between jobs

on:
  workflow_run:
    workflows: ["Share data between jobs"]
    types: [completed]

jobs:
  job_2:
    name: Multiply by 9
    runs-on: windows-latest
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v2
        with:
          name: homework
      - shell: bash
        run: |
          value=`cat math-homework.txt`
          expr $value \* 9 > math-homework.txt
      - name: Upload math result for job 2
        uses: actions/upload-artifact@v2
        with:
          name: homework
          path: math-homework.txt
